### ISSUE TITLE
when to release the dataset?

### ISSUE THREAD

**Issue by peggypytang** [yingtaomj/VMSMO#2]
Hello, when will the dataset be released? Thanks.

**Comment by yingtaomj** [comment]
Hi, we are now releasing the link to download each case in the dataset. Full dataset is coming soon.

**Comment by peggypytang** [comment]
When will the full dataset be released?

**Comment by peggypytang** [comment]
Hi, is there any update on the full dataset / any planned release date? Thank you.

**Comment by PipiZong** [comment]
> Hi, we are now releasing the link to download each case in the dataset. Full dataset is coming soon.

Hi, could you please give some demo samples so we could run through the code? Or could you please release the preprocessing code to get the text features and video features? Thanks!

**Comment by yingtaomj** [comment]
Hi, we now add the preprocess codes and give instructions on how to use that in readme.
