### ISSUE TITLE
An Keyerror when run the code

### ISSUE THREAD

**Issue by StudentbyTheSea** [yingtaomj/VMSMO#3]
Hello,  i have run the code and I wonder  if the train.json have some missing part like 'start' ,'end' ,'max_sim'?Thank you very much!

**Comment by yingtaomj** [comment]
In our implementation, we store all the video features in one file (VF file) to speed up the training process. Hence, to establish the relationship between video file and text file, in each case in the train.json file, we store its start feature index and end feature index in the VF. max_sim index denotes the index of the cover image of the current case.

**Comment by PipiZong** [comment]
> In our implementation, we store all the video features in one file (VF file) to speed up the training process. Hence, to establish the relationship between video file and text file, in each case in the train.json file, we store its start feature index and end feature index in the VF. max_sim index denotes the index of the cover image of the current case.

Hello,

Thanks for your recent updates! And sorry to bother you.
Could you please also share with us the specific files for data/test/vocab_path required in 'python run_summarization.py --mode=train --data_path=* --test_path=* --vocab_path=* --log_root=logs --exp_name=vmsmo --max_enc_steps=100 --max_dec_stpes=30 --vocab_size=50000 --lr=0.001'? It's still hard to reproduce the result in your paper according to the readme...And in your paper, it states ' 10 cover candidates are selected  from every 120 frames', could you also help point out where this implementation is in your code? 
Thank you!
