### ISSUE TITLE
403 when trying to download videos and images

### ISSUE THREAD

**Issue by mateuk** [yingtaomj/VMSMO#4]
Hello, I'm trying to download the dataset.
However, I encountered a problem when trying to download anything from some of the domains, mainly  `miaopai.video.weibocdn.com`, which contains most of the links. I keep on getting the following response:
```<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<h1>403 Forbidden</h1>
<p>You don't have permission to access the URL on this server.<hr/>Powered by Tengine</body>
</html>
```
I attach [a list of links that worked](https://github.com/yingtaomj/VMSMO/files/5906188/dev_ok.txt) and [list of links which didn't](https://github.com/yingtaomj/VMSMO/files/5906183/dev_faulty.txt) from the dev set.

Any ideas on what could be the reason? Is it possible that some kind of authorization is required?

**Comment by StudentbyTheSea** [comment]
hello,I have the same problem as you .How do you preprocess the video and image before train ? thanks

**Comment by yingtaomj** [comment]
Hi, we checked the links, and it seems that some of the links have been out of date. So we provide the crawler code in the weibo-crawler folder, by which you can used to collect more new data.
